name: User List Githib CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        
        with:
          node-version: '22'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🌐 Start Application
        run: npm run start &  # Uygulamayı arka planda başlatır

      - name: 🧪 Run Cypress Tests
        with:
          start: npx cypress run
          browser: chrome